#!/sbin/sh
# Script for booting into recovery
# Author: nobodyAtall @ xda

recovery() {
	# fixing CPU clocks to avoid issues in recovery
	echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo 600000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	echo 122880 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
	rm /cache/recovery/boot
	mount -o remount,rw rootfs /
	umount -l /system
	umount -l /data
	umount -l /cache
	umount -l /mnt/sdcard
	rm -r /sdcard
	rm -r /not/sdcard
	mkdir /sdcard
	mkdir /tmp
	rm /etc
	mkdir /etc
	cp /recovery.fstab /etc/recovery.fstab
	mount /dev/block/mmcblk0p1 /sdcard
	rm -rf /tmp/*
	pkill bootlogo
	/sbin/recovery &
	/sbin/adbd recovery 
}

copy_modules() {
	for x in `ls /modules/`
	do
		MD5SUM1=`md5sum /modules/$x | awk {'print $1'}`
		MD5SUM2=`md5sum /system/lib/modules/$x | awk {'print $1'}`
		if [ "$MD5SUM1" != "$MD5SUM2" ]
		then
			cp /modules/$x /system/lib/modules/$x
		fi
	done
}

cleanup() {
	mount -o remount,rw /
	RECVERSION=`strings /sbin/recovery|/system/xbin/grep Recovery | /system/xbin/head -n 1`
	rm -rf `ls /sbin/* | grep -v adb |grep -v charger` /modules /res
	echo $RECVERSION > /sbin/recovery
	mount -o remount,ro /
}

if [ -e /cache/recovery/boot ]
then
	recovery
else
	sleep 1
	kill -9 $(cat /dev/keycheck.pid)
	if [ -s /dev/keycheck ]
	then
		recovery
	else
		mount -o remount,rw /system
		mkdir -p /system/lib/modules/
		copy_modules
		mount -o remount,ro /system
		cleanup
	fi
fi
