#!/sbin/sh
# Script for capturing keypad input and booting into recovery
# Author: nobodyAtall @ xda
exec /sbin/nice -n -20 /sbin/bootlogo &
keypad_input=''
for input in `ls -d /sys/class/input/input*`
do
	type=`cat ${input}/name`
	case "$type" in
    (*keypad*) keypad_input=`echo $input | sed 's/^.*input//'`;;
    (*cyttsp*) touch_input=`echo $input | sed 's/^.*input//'`;;
    (*synaptic*) touch_input=`echo $input | sed 's/^.*input//'`;;
    (*)        ;;
    esac
done
cat /dev/input/event${keypad_input} > /dev/keycheck&
cat /dev/input/event${touch_input} > /dev/tscheck&
